server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: verdora-backend

  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: [ email, profile ]

app:
  oauth2:
    redirect-uri: ${REDIRECT_URL:http://localhost:5173}
  jwt:
    secret: ${JWT_SECRET:3qzqVSvMGFVncul6arlN0Na0F/YcSbmJyvICg43Q2cQ=}
    access-expiration-ms: 900000 # 15 min
    refresh-expiration-ms: 604800000 # 7 days