ALTER TABLE orders
    DROP CONSTRAINT IF EXISTS orders_status_check;

ALTER TABLE orders
    DROP CONSTRAINT IF EXISTS "CONSTRAINT_C3D";

ALTER TABLE orders
    ADD CONSTRAINT orders_status_check
        CHECK (status IN ('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED'));